name: pro-pla-local
services:
  c-postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - c-postgres:/var/lib/postgresql/data
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres-pwd
    healthcheck:
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10
    labels:
      org.springframework.boot.service-connection: postgres
      org.springframework.boot.readiness-check.tcp.disable: true

volumes:
  c-postgres: