spring:
  application:
    name: MyArchitecture
  profiles:
    active: standalone
management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: '/apis'